// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDRCOxCFwb-4OaYy0SC8giJtcdkupIiRAw',
    appId: '1:31449495880:web:fd2ae49804450266da5b7d',
    messagingSenderId: '31449495880',
    projectId: 'beat-bazaar-1320',
    authDomain: 'beat-bazaar-1320.firebaseapp.com',
    storageBucket: 'beat-bazaar-1320.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBLeZ-C5oVdrUCOjLsv_9e-Lek5Jv_SyF0',
    appId: '1:31449495880:android:61251045c413c152da5b7d',
    messagingSenderId: '31449495880',
    projectId: 'beat-bazaar-1320',
    storageBucket: 'beat-bazaar-1320.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCKPj5-kL7bFpYIO25cRpyN88gFwn1Bk_g',
    appId: '1:31449495880:ios:4bafec987ba36786da5b7d',
    messagingSenderId: '31449495880',
    projectId: 'beat-bazaar-1320',
    storageBucket: 'beat-bazaar-1320.appspot.com',
    iosBundleId: 'com.example.beatBazaar',
  );
}
